# Generated by Django 5.1.7 on 2025-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
