# Generated by Django 5.1.7 on 2025-06-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_intens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intens',
            new_name='Iten',
        ),
    ]
